site_name: Ranvier
site_description: "Ranvier is a Node.js-based MUD codebase built for modularity, extensibility and getting up-and-running in the least amount of time possible."
copyright: Copyright &copy; 2017, Shawn Biddle
site_author: Shawn Biddle
docs_dir: docs
site_dir: ../site
repo_url: https://github.com/RanvierMUD/ranviermud
theme:
    name: null
    custom_dir: docs/_mkdocs/theme/ranvier
extra:
    logo: '_static/images/logo.png'
extra_css: 
    - _mkdocs/theme/ranvier/assets/stylesheets/application.css
    - _mkdocs/theme/ranvier/assets/stylesheets/application.palette.css
markdown_extensions:
    - def_list
    - codehilite
    - toc:
        permalink: true
        title: 'Contents'
    - pymdownx.tasklist:
        custom_checkbox: true
google_analytics: ["UA-28253658-1", "auto"]

pages:
- Overview: 'index.md'
- Get Started: 'get_started.md'
- Release Notes: 'release_notes.md'
- Bundles: 'bundles.md'
- Building:
    - Creating an Area: 'building/index.md'
    - Items: 'building/items.md'
    - NPCs: 'building/npcs.md'
    - Rooms: 'building/rooms.md'
    - Quests: 'building/quests.md'
    - Scripting: 'building/scripting.md'
- Coding:
    - Attributes: 'coding/attributes.md'
    - Server Events: 'coding/server.md'
    - Channels: 'coding/channels.md'
    - Classes/Abilities: 'coding/classes.md'
    - Commands: 'coding/commands.md'
    - Effects: 'coding/effects.md'
    - Player/Input Events: 'coding/input_events.md'
    - From Scratch: 'coding/from_scratch.md'
- Extending:
    - Entity Loaders: 'extending/entity_loaders.md'
- Contributing: 'contributing.md'
- License/Credits: 'license.md'
